### ISSUE TITLE
Some Errors that i find

### ISSUE THREAD

**Issue by Arturojl** [dragoonDorise/RP-Switch#1]
1.You cant play games from favorites or recent games.
2.if you dont have favorites games and enter to the favorite section, you cant go back to the menu. you need to close pegasus

**Comment by dragoonDorise** [comment]
Hi @Arturojl , both issues has been fixed as of 1.0.1 : https://github.com/dragoonDorise/RP-Switch/releases/latest

Thanks for your feedback!
