### ISSUE TITLE
games doesnt start in any collection

### ISSUE THREAD

**Issue by Arturojl** [dragoonDorise/RP-Switch#2]
here a demostration:
https://youtu.be/aXjYOe2Rkd4
i am using the 1.0.1

**Comment by dragoonDorise** [comment]
Please download 1.0.2, its fixed there.

There is still a bug with the search in 1.0.2 , so you might want to wait for 1.0.3

**Comment by dragoonDorise** [comment]
Hi 1.0.3 is available, please download it!

https://github.com/dragoonDorise/RP-Switch/releases/tag/1.0.3

**Comment by Arturojl** [comment]
downloading 1.0.3 thanks a lot :D
