### ISSUE TITLE
Can't show battery indicator without messing up theme

### ISSUE THREAD

**Issue by basvroegop** [dragoonDorise/RP-Switch#3]
Hi,

First up: great job on this theme! Seems to have all the tweaks to make it run nicely on the RP2.

I did notice one little problem with it. If you're not running it in fullscreen mode, the bottom part gets clipped off. Which kind of sucks: disabling full screen is the only way to consistently show the battery indicator in the top right.

Would it be possible to fix the clipping? Or even better: maybe add a battery indicator in the theme itself?

Thanks!

**Comment by dragoonDorise** [comment]
Hi @basvroegop , thanks for your support!

I'm happy to announce that as of 1.0.5 the clipping is gone! Now you can browse your games and see battery status.

https://github.com/dragoonDorise/RP-Switch/releases/latest

**Comment by basvroegop** [comment]
Awesome, thanks!
