### ISSUE TITLE
Starting a searched game boots up the wrong one

### ISSUE THREAD

**Issue by basvroegop** [dragoonDorise/RP-Switch#4]
Ran into a small bug: when searching for a game and selecting the one I want to play, it boots up the wrong one. For example: Policenauts in the PSX collection starts up a Neo Geo Pocket Color RPG, while Golden Sun boots up Arc the Lad on PSX.

All games work fine when selecting without search filtering the list down, so it seems to be search related.

**Comment by dragoonDorise** [comment]
Hi @basvroegop , this should be fixed since 1.0.4, did you installed 1.0.5 and then restarted pegasus?

**Comment by basvroegop** [comment]
Ah, I totally missed 1.0.4 getting released as well. You're really pumping them out, haha. I'll check when I've got time and will get back to you, but guessing it's already fixed!

**Comment by dragoonDorise** [comment]
I don’t have a lot of free time so I have to try to fix all the bugs at once when I have a little bit of time at the weekend  or I’ll never get another chance to fix them! Hope everything works fine for you
