### ISSUE TITLE
Game's Title does not appear on top of the game selected

### ISSUE THREAD

**Issue by CeeNain** [dragoonDorise/RP-Switch#5]
Hi! I was wondering if it's intended for the games not to show the game's title when selecting it. I considered it to be quite useful to write in information when having different rom hacks based on the same game. The original SwitchOS theme by PlayingKarrde had this option.

![image](https://user-images.githubusercontent.com/74126204/98456987-8228b580-2148-11eb-8eeb-d717c26c5c48.png)

**Comment by dragoonDorise** [comment]
Sure, I’ll make the change for the next release

**Comment by dragoonDorise** [comment]
Hi @CeeNain , this should be fixed as of 1.06: https://github.com/dragoonDorise/RP-Switch/releases/tag/1.0.6
