### ISSUE TITLE
Screenshots stretch vertically to fit its square

### ISSUE THREAD

**Issue by CeeNain** [dragoonDorise/RP-Switch#6]
Screenshots for games stretch to fit the square. I by no means mean to compare, since you're work is awesome, but on PlayingKarrde's and Valsou's SwitchOS versions the images fit vertically to avoid stretched images. I'm attaching two photos (sorry for the low quality). One photo is from your version of SwitchOS and one is from Valsou's version.
![Valsou Fork](https://user-images.githubusercontent.com/74126204/98457114-19dad380-214a-11eb-9d33-1a2e06d85d65.jpeg)
![RP Switch Theme](https://user-images.githubusercontent.com/74126204/98457115-1a736a00-214a-11eb-8b04-c79547c2b0ba.jpeg)

**Comment by dragoonDorise** [comment]
Hi @CeeNain , I’ll try to fix it next weekend!

**Comment by dragoonDorise** [comment]
Hi @CeeNain , this should be fixed as of 1.06: https://github.com/dragoonDorise/RP-Switch/releases/tag/1.0.6
