### ISSUE TITLE
System logo boxes appears blank

### ISSUE THREAD

**Issue by ricochiretroid** [dragoonDorise/RP-Switch#8]
Hi! This theme is absolutely awesome. Just have some issues with it... maybe you could help me:

1. NeoGeo Pocket/Color games appears under "DOS" system, and there is no boxed image of system (it appears blank)

2. Scummvm and Wonderswan systems has no logo box, it appears blank also.

Many thanks!

**Comment by dragoonDorise** [comment]
Hey, that's probably a metadata problem, check the Pegasus metadata file, I did a new metadata pack: https://github.com/dragoonDorise/pegasus-android-metadata and a new automatic installer: https://www.pegasus-installer.com
